# n8n development / workflow playground on Render

services:
  - type: web

    # 1 CPU / 2 GB RAM
    # Recommended by Render for n8n
    plan: 1c-2g

    runtime: image
    name: n8n-service

    image:
      # Better than :latest for a development environment.
      # Once you're happy with a version, keep it pinned.
      url: docker.io/n8nio/n8n:latest

    envVars:

      # IMPORTANT:
      # Never change this after credentials have been created.
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # n8n's default HTTP port
      - key: PORT
        value: "5678"

      # Database
      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database

      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host

      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password

      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user


databases:
  - name: n8n-db
    plan: free
